### ISSUE TITLE
-Inf/Inf should be formatted as -infinity/infinity

### ISSUE THREAD

**Issue by KES777** [houseabsolute/DateTime.pm#121] opened 2021-05-29 15:14 UTC
For my objects I set formatter as `->set_formatter( 'DateTime::Format::Pg' )`

But get error: `ERROR:  invalid input syntax for type timestamp with time zone: "'-Inf'"`

I do not which of modules should care about stringification. So I create issue here.

Details are here https://github.com/lestrrat-p5/DateTime-Format-Pg/issues/22#issue-906493655

**Comment by autarch** [comment] 2021-05-29 15:16
AFAIK, the way that infinity is stringified is system-dependent. But specific formatter modules should format it in the way that works for whatever format it implements.

I'm going to close this, since DateTime itself shouldn't be dealing with this.

**Closed by autarch** 2021-05-29 15:16 UTC

**Comment by KES777** [comment] 2021-05-29 15:32
Actually I do not see how you call defined formater:

![image](https://user-images.githubusercontent.com/799021/120075976-2e61c780-c0ac-11eb-9493-5576d5f2ddf3.png)

**Comment by autarch** [comment] 2021-05-29 15:36
The formatter is only called for stringification of the entire DateTime, not for individual elements. But if you're interfacing with an external system, I'd strongly encourage you to explicitly use the formatter, so something like:

```perl
my $formatted = DateTime::Format::Pg->format_datetime($dt);
```

This is much more explicit (and therefore clear) than creating a DateTime object with a formatter in one place and stringifying it elsewhere. It also lets you easily format the same DateTime object in different ways.

**Comment by KES777** [comment] 2021-05-29 15:41
I can not format it manually, because DBIx::Class::InflateColumn::DateTime do this when DateTime object go into database.
I do not understand about what you mean about `individual elements`. I just do next:

```perl

my $dt =  DateTime::Format::Pg->parse_datetime( '-infinity' )->set_formatter( 'DateTime::Format::Pg' );
print "$dt"; # Must be '-infinity', actual '-Inf'
```

**Comment by autarch** [comment] 2021-05-29 15:46
`DBIx::Class::InflateColumn::DateTime` explicitly calls `DateTime::Format::Pg->format_datetime` when serializing a `DateTime` object. I'm really not sure what the problem is, actually, because looking at `DateTime::Format::Pg`, I can see it handles infinite objects correctly - https://metacpan.org/release/DateTime-Format-Pg/source/lib/DateTime/Format/Pg.pm#L785

I _think_ what might be happening is that you are somehow stringifying your `DateTime` object yourself somewhere in your code, so DBIC never calls `DateTime::Format::Pg`, because it just sees a string.

But again, this has nothing to do with how `DateTime` itself works.

**Comment by KES777** [comment] 2021-05-29 15:47
`DateTime::Infinite` isa `DateTime` and must not change `sub stringify` behaviour.

Please try this example: `"". DateTime::Format::Pg->parse_datetime( '-infinity' )->set_formatter( 'DateTime::Format::Pg' )`

**Comment by KES777** [comment] 2021-05-29 15:53
>DBIx::Class::InflateColumn::DateTime explicitly calls DateTime::Format::Pg->format_datetime

Also it could be it calls directly because your object strigification does not work correct

**Comment by KES777** [comment] 2021-05-29 16:02
To my mind here you are trying to stringify `DateTime::INFINITY` and not current object `$self`

https://github.com/houseabsolute/DateTime.pm/blob/master/lib/DateTime/Infinite.pm#L67
