### ISSUE TITLE
Performance regressions due to Specio

### ISSUE THREAD

**Issue by versable** [houseabsolute/DateTime.pm#85] opened 2018-10-25 12:02 UTC
Hey, first and foremost, thanks for DateTime. I have worked on custom date/time libraries in the past and I really appreciate not going through that experience again, not my cup of tea, way too complicated and too many edge cases/pitfalls.

Saying that, we are updating our infrastructure and ran into performance regressions. We noticed our application was running a bit slower on the updated platform.

After debugging with Devel::NYTProf [1] and inspecting the stack call flamegraph [2][3], we noticed that loading DateTime took 77.79% (from consuming 1.89% of our application to 8.47%) more time than previously. After investigating it was clear that this regression was introduced with commit 3308e9ede624f063892b26a2f8a21a9c4c5bb99c.

[1] https://metacpan.org/pod/Devel::NYTProf
[2] http://www.brendangregg.com/flamegraphs.html
[3] https://github.com/brendangregg/FlameGraph

Screencaps before the regression:
![dt-params](https://user-images.githubusercontent.com/4646630/47498731-69e5e680-d85e-11e8-9f52-eddbf08c7c0e.png)

![dt-params-time](https://user-images.githubusercontent.com/4646630/47498740-6f433100-d85e-11e8-8f18-2417fdef2669.png)

Screencaps after the regression:
![dt-specio](https://user-images.githubusercontent.com/4646630/47498754-7407e500-d85e-11e8-8676-1f620616426d.png)

![dt-specio-time](https://user-images.githubusercontent.com/4646630/47498759-79652f80-d85e-11e8-86c3-4079bef0f37d.png)

![dt-specia-validate-time](https://user-images.githubusercontent.com/4646630/47501651-4cb51600-d866-11e8-9105-4796c2966ee4.png)

**Comment by autarch** [comment] 2018-10-25 14:47
Thanks for the report.

Just to clarify. This output is purely about the _load_ time of the module, not its runtime performance, right?

The fact that it loads more slowly is something I already knew. However, I felt that this was worth it given that Specio led to a 14% improvement in object construction speed. See https://blog.urth.org/2016/06/05/making-datetime-faster-and-slower/ for my own benchmarking from back when I first worked on switching to Specio.

If you have any thoughts on how to speed up the load time, I'd be all for it. Looking at the profile, it seems like this mostly comes down to two things. The first is that it's loading many more modules. Most of those load very quickly.

The second is that there's a lot of time spent in `Specio::OO`. This isn't surprising, since that particular module is used at load time by most of the other modules being loaded. It calls `eval` many times to create constructors and attribute accessor methods for the caller. Off hand, I don't see any obvious way to speed this up, but I haven't really looked into it much.

**Comment by autarch** [comment] 2018-10-26 17:11
Also, can you share whatever code you profiled? I'm not sure exactly how to reproduce that locally. Note that I know how to use NYTProf, I'm just asking what you profiled.

**Comment by autarch** [comment] 2018-10-26 17:16
So I investigated this a bit and I can optimize Specio's load time a _small_ amount, but I don't think it would ever be possible to make DateTime as fast to load as it used to be. That said, as I noted in my blog post, I think it's much more useful to optimize DateTime's runtime performance, and using Params::ValidationCompiler and Specio made quite an improvement there.

**Comment by autarch** [comment] 2019-01-04 15:52
I'm going to close this since it's not really actionable at this point. PRs to speed up load time for DateTime, Specio, or any other deps I work on would be welcome.

**Closed by autarch** 2019-01-04 15:52 UTC
