### ISSUE TITLE
calculated last day of month wrong

### ISSUE THREAD

**Issue by cristianstocco** [houseabsolute/DateTime.pm#120] opened 2021-05-03 09:06 UTC
Hello,

I've tested the functionality of ->add() and ->substract->() and I've noticed an error of calculating the last day of a month.
Here my code:

```
my $dt = DateTime->now;
my $nDayInMonth = $dt->day;
$dt->add( {days => -$nDayInMonth+1} ); #first day of month
$dt->add( {days => -1, months => 1} ); #last day of month
```

I've noticed that there is the function last_day_of_month but this calculation is obviously wrong.
Thinking that it should be working for bot sides.

Thank you,
Cristian Stocco

**Comment by n1vux** [comment] 2021-05-03 18:57
In general, adding Months is one of the most fraught corners of date arithmetic. Basically adding "months" is **un**obviously wrong pretty much whenever it's used. People have different intuitions depending on what they're thinking at the moment, but the code can't tell which intention was intended. So the code has to pick one and be consistent. Which will often be wrong. 


Does 2nd Tuesday + 1 month = next 2nd Tuesday? 
Does Last Day + 1 month = next  Last Day?
Does it mean `$dt->$month++` , change DoW and hold day number constant?  ✓
If so, does `DateTime->last_day_of(month=>5,year=>2021)->add{months=>1})` result in 6/30 or 7/01✓ or a runtime error? 
But even if it "carries" from 6/31 to 7/01 (✓it does), it can't intuit whether  4/30 + 1 month = 5/30 should "round up" to 5/31 or not, as that depends on the **intention** of 30th day of or last of.

 _SWYM_=Say What You Mean.
 
If you mean `last_day_of_month()`, use that.

If you want 30th to 30th, go ahead and use the arithmetic and just be warned that 31st may wrap to 1st when there isn't one (and 29, 30 on February!). 

Your code to find the first day appears correct but is the equivalent of
```
$dt=DateTime->today->set_day(1);             #first day of month
```
(which is why there isn't a `first_day_of_month()` in symmetry with the last-day convenience constructor; it's nearly redundant, a simple transparent idiom suffices. And yes, if you are doing only Date arithmetic and not timestamps too, it's better to use `today` than `now`.)

If you really want to compute `last_day_of_month` from a `$dt` without going through the convenience constructor `$dt = DateTime->last_day_of_month(month=>$dt->month, year=>$dt->year)` you need to go forward to go back, not back to go forward:

```
my $dt = DateTime->today;
$dt->add({months=>1})->set_day(1)->add({days=>-1}); 
say $dt;
```

But that's less efficient and less explicit.

**Comment by autarch** [comment] 2021-05-03 20:14
See https://metacpan.org/pod/DateTime#How-DateTime-Math-Works for a lot more details about this topic.

I'm going to close this issue since there is no bug here.

**Closed by autarch** 2021-05-03 20:14 UTC
